language: cpp

notifications:
  email: false

sudo: required

compiler: gcc

os: linux

before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - cmake --version

script:
  - mkdir build && cd build
  - cmake .. && make -j8
  - ./bin/shaders_factory_test
