language: cpp

notifications:
  email: false

sudo: required

compiler: gcc

os: linux

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

script:
  - mkdir build && cd build
  - cmake .. && make -j8
  - ./bin/shaders_factory_test
